ORG 0000H
MOV TMOD,#10H 
BACK:MOV TL1,#0A2H
	 MOV TH1,#0FFH
	 CLR P2.3
ACALL DELAY
	MOV TL1,#0A2H
	MOV TH1,#0FFH
	SETB P2.3
ACALL DELAY
    SJMP BACK
DELAY:SETB TR1
AGAIN:JNB TF1,AGAIN
	  CLR TR1
	  CLR TF1
	  RET ;RETURNS TO Ton CYCLE FROM ACALL DELAY
END