ORG 0000H
ITER:MOV R0,#30H
	MOV R1,#31H
	MOV R2,#04
	MOV R3,#04
	OPER:MOV A,@R0
		MOV B,@R1
		CJNE A,B,CHECK ; DO JC FOR ASCENDING AND JNC FOR DESCENDING 
	CHECK:JC NOEXCH ;C=0 DO XCH OR C=1 NO XCH
		XCH A,B
		MOV @R0,A
		MOV @R1,B
	NOEXCH:INC R0
		INC R1
		DJNZ R2,OPER
		DJNZ R3,ITER
HERE:SJMP HERE
END