ORG 0000H
MOV R0,#3CH ;3C MEMORY ADDRESS ASSIGNED TO R0
MOV @R0,#3  ;BINARY NO. 3 TO MEMORY AT 3CH
MOV A,@R0   ;MOVE THE CONTENTS OF RAM LOCATION R0 TO A

MOV DPTR,#9000H ;ADDRESS OF EXTERNAL MEMORY
MOVX A,@DPTR ;MOV CONTENT TO A FROM ADDRESS LOCATION OF DPTR
END